name: Auto Label by Title Prefix

on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply task label
        if: startsWith(github.event.issue.title, '[TASK]')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.PROJECT_TOKEN }}
          labels: task

      - name: Apply bug label
        if: startsWith(github.event.issue.title, '[BUG]')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.PROJECT_TOKEN }}
          labels: bug